#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop minecraft
systemctl stop minecraft

# Backup sources & data
# Note: the last argument is where to save this path, see the restore script.
ynh_backup "/home/yunohost.app/${app}" "sources"

# Start minecraft
systemctl start minecraft
