#!/bin/bash

# Note: each files and directories you've saved using the ynh_backup helper
# will be located in the current directory, regarding the last argument.

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop minecraft
systemctl stop minecraft

# Restore sources & data
src_path="/home/yunohost.app/${app}"
cp -a ./sources "$src_path"

# Restore permissions to app files
# you may need to make some file and/or directory writeable by www-data (nginx user)
chown -R $app $final_path

# Restart minecraft
systemctl start minecraft
